### ISSUE TITLE
Cannot reproduce second README example

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#56]
Using these files that I save in `data`:

https://aloftdata.s3-eu-west-1.amazonaws.com/baltrad/hdf5/nldbl/2013/11/23/nldbl_vp_20131123T0000Z.h5
https://aloftdata.s3-eu-west-1.amazonaws.com/baltrad/hdf5/nldbl/2013/11/23/nldbl_vp_20131123T0015Z.h5
https://aloftdata.s3-eu-west-1.amazonaws.com/baltrad/hdf5/nldbl/2013/11/23/nldbl_vp_20131123T0030Z.h5

I get an error if I want to reproduce the second README example:

```python
from pathlib import Path
from vptstools.vpts import vpts

file_paths = sorted(Path("./data").rglob("*.h5"))  # Get all h5 files within the data directory
df_vpts = vpts(file_paths)
```

```ini
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/peter_desmet/Coding/Repositories/enram/vptstools/test.py", line 5, in <module>
    df_vpts = vpts(file_paths)
              ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vptstools/vpts.py", line 256, in vpts
    with multiprocessing.Pool(processes=cpu_count) as pool:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I print `file_paths` I get:

```
[PosixPath('data/nldbl_vp_20131123T0000Z.h5'), PosixPath('data/nldbl_vp_20131123T0015Z.h5'), PosixPath('data/nldbl_vp_20131123T0030Z.h5')]
```

**Comment by stijnvanhoey** [comment]
I tested the code for these files in both Python 3.9 and 3.11 and I can not reproduce the error.  It is also strange the `release` github action which checks for 3.11 on macos does not report an error. 

![image](https://github.com/enram/vptstools/assets/754862/7e3e272a-6418-4032-817f-afd4a9b71343)

Could you specify the error itself that is raised?

**Comment by peterdesmet** [comment]
Hmm, if I run this from the command line `python3 my_script.py` I get the error, but not in a Jupyter notebook. So I would ignore the error.
